name: halkaphulka1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_core:
  google_fonts: ^1.0.0
  cloud_firestore: ^0.13.7
  firebase_auth:
  google_sign_in:
  camera:
  curved_navigation_bar:
  flutter_swiper:
  progress_indicators:
  share:
  video_player:
  flutter_facebook_login: ^3.0.0
  cached_network_image:
  shared_preferences:
  flutter_advanced_networkimage: ^0.7.0
  flushbar:
  firebase_storage:
  image_picker: ^0.6.7+2
  image_cropper: ^1.2.3
  toggle_switch:
  flutter_launcher_icons: ^0.7.5
  http:
  path_provider:
  camera_camera: ^1.0.34+1
  video_trimmer: ^0.2.4
  flutter_ffmpeg: ^0.2.10
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/ic_flutter_devs_logo.png
    - assets/images/ic_powered_by.png
    - assets/images/ic_switch_camera_3.png
    - assets/images/ic_no_video.png
    - assets/images/ic_play.png
    - assets/images/ic_stop_video.png
    - assets/images/ic_video_shutter.png
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
